/*
 Programmer:
 Date:
 Program Name: Matching Game Solution
 Program Description: This program uses arrays to simulate a matching game.
 * A grid of cards will be displayed and the user is to select 2 cards at a time
 * looking for matching cards. The goal of this game is to see how quickly
 * the user can find all the matches.
 */
package memorygame;

import java.util.ArrayList;
import javax.swing.ImageIcon;

/**
 *
 * @author U410
 */
public class MemoryUI extends javax.swing.JFrame {

    ArrayList<String> cards = new ArrayList();
    ArrayList<String> set = new ArrayList();
    ImageIcon a = new ImageIcon("ram.jpg");
    ImageIcon b = new ImageIcon("case.jpg");
    ImageIcon c = new ImageIcon("dvd.jpg");
    ImageIcon d = new ImageIcon("harddrive.jpg");
    ImageIcon e = new ImageIcon("keyboard.jpg");
    ImageIcon f = new ImageIcon("mice.jpg");
    ImageIcon g = new ImageIcon("monitor.jpg");
    ImageIcon h = new ImageIcon("printer.jpg");
    ImageIcon back = new ImageIcon("cardback.jpg");
    ImageIcon done = new ImageIcon("done.jpg");
    int count, c1, c2, card1, card2;
    int cardsLeft = 16;
    int[] change = new int[16];

    /**
     * Creates new form MemoryUI
     */
    public MemoryUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        card1Button = new javax.swing.JButton();
        card2Button = new javax.swing.JButton();
        card3Button = new javax.swing.JButton();
        card4Button = new javax.swing.JButton();
        card5Button = new javax.swing.JButton();
        card6Button = new javax.swing.JButton();
        card7Button = new javax.swing.JButton();
        card8Button = new javax.swing.JButton();
        card9Button = new javax.swing.JButton();
        card10Button = new javax.swing.JButton();
        card11Button = new javax.swing.JButton();
        card12Button = new javax.swing.JButton();
        card13Button = new javax.swing.JButton();
        card14Button = new javax.swing.JButton();
        card15Button = new javax.swing.JButton();
        card16Button = new javax.swing.JButton();
        playButton = new javax.swing.JButton();
        guessButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        outputLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titleLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(255, 0, 51));
        titleLabel.setText("Matching Game");

        card1Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/memorygame/cardback.jpg"))); // NOI18N
        card1Button.setText("jButton1");
        card1Button.setPreferredSize(new java.awt.Dimension(75, 75));
        card1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                card1ButtonActionPerformed(evt);
            }
        });

        card2Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/memorygame/cardback.jpg"))); // NOI18N
        card2Button.setText("jButton1");
        card2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                card2ButtonActionPerformed(evt);
            }
        });

        card3Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/memorygame/cardback.jpg"))); // NOI18N
        card3Button.setText("jButton1");
        card3Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                card3ButtonActionPerformed(evt);
            }
        });

        card4Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/memorygame/cardback.jpg"))); // NOI18N
        card4Button.setText("jButton1");
        card4Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                card4ButtonActionPerformed(evt);
            }
        });

        card5Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/memorygame/cardback.jpg"))); // NOI18N
        card5Button.setText("jButton1");
        card5Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                card5ButtonActionPerformed(evt);
            }
        });

        card6Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/memorygame/cardback.jpg"))); // NOI18N
        card6Button.setText("jButton1");
        card6Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                card6ButtonActionPerformed(evt);
            }
        });

        card7Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/memorygame/cardback.jpg"))); // NOI18N
        card7Button.setText("jButton1");
        card7Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                card7ButtonActionPerformed(evt);
            }
        });

        card8Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/memorygame/cardback.jpg"))); // NOI18N
        card8Button.setText("jButton1");
        card8Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                card8ButtonActionPerformed(evt);
            }
        });

        card9Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/memorygame/cardback.jpg"))); // NOI18N
        card9Button.setText("jButton1");
        card9Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                card9ButtonActionPerformed(evt);
            }
        });

        card10Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/memorygame/cardback.jpg"))); // NOI18N
        card10Button.setText("jButton1");
        card10Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                card10ButtonActionPerformed(evt);
            }
        });

        card11Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/memorygame/cardback.jpg"))); // NOI18N
        card11Button.setText("jButton1");
        card11Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                card11ButtonActionPerformed(evt);
            }
        });

        card12Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/memorygame/cardback.jpg"))); // NOI18N
        card12Button.setText("jButton1");
        card12Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                card12ButtonActionPerformed(evt);
            }
        });

        card13Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/memorygame/cardback.jpg"))); // NOI18N
        card13Button.setText("jButton1");
        card13Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                card13ButtonActionPerformed(evt);
            }
        });

        card14Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/memorygame/cardback.jpg"))); // NOI18N
        card14Button.setText("jButton1");
        card14Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                card14ButtonActionPerformed(evt);
            }
        });

        card15Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/memorygame/cardback.jpg"))); // NOI18N
        card15Button.setText("jButton1");
        card15Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                card15ButtonActionPerformed(evt);
            }
        });

        card16Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/memorygame/cardback.jpg"))); // NOI18N
        card16Button.setText("jButton1");
        card16Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                card16ButtonActionPerformed(evt);
            }
        });

        playButton.setText("Play");
        playButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playButtonActionPerformed(evt);
            }
        });

        guessButton.setText("Guess");
        guessButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guessButtonActionPerformed(evt);
            }
        });

        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        outputLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        outputLabel.setText("Click Play button to start. Click Guess Again after each guess.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(titleLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(card5Button, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(card9Button, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(card13Button, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(card6Button, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(card10Button, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(card14Button, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(card7Button, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(card11Button, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(card15Button, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(card8Button, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(card12Button, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(card16Button, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addComponent(playButton)
                                .addGap(27, 27, 27)
                                .addComponent(guessButton)
                                .addGap(29, 29, 29)
                                .addComponent(exitButton))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(card1Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23)
                                .addComponent(card2Button, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25)
                                .addComponent(card3Button, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(card4Button, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(31, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(outputLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(titleLabel)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(card1Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(card2Button, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(card3Button, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(card4Button, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(card5Button, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(card6Button, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(card7Button, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(card8Button, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(card9Button, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(card10Button, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(card11Button, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(card12Button, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(card13Button, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(card14Button, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(card15Button, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(card16Button, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(playButton, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(guessButton, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(outputLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void playButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playButtonActionPerformed
        //set change array
        for (int z = 0; z <= 15; z++) {
            change[z] = 1;
        }
        String temp;
        for (int x = 0; x <= 7; x++) {
            for (int y = 1; y <= 2; y++) {
                temp = Integer.toString(x);
                set.add(temp);
            }
        }
        for (int x = 0; x <= 15; x++) {
            double index = Math.floor(Math.random() * (16 - x));
            int index1 = (int) index;
            cards.add(set.get(index1));
            set.remove(set.get(index1));
        }
    }//GEN-LAST:event_playButtonActionPerformed

    private void card1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_card1ButtonActionPerformed
        String temp = cards.get(0);

        if (temp.equals("0")) {
            card1Button.setIcon(a);
        } else if (temp.equals("1")) {
            card1Button.setIcon(b);
        } else if (temp.equals("2")) {
            card1Button.setIcon(c);
        } else if (temp.equals("3")) {
            card1Button.setIcon(d);
        } else if (temp.equals("4")) {
            card1Button.setIcon(e);
        } else if (temp.equals("5")) {
            card1Button.setIcon(f);
        } else if (temp.equals("6")) {
            card1Button.setIcon(g);
        } else if (temp.equals("7")) {
            card1Button.setIcon(h);
        }

        count++;
        if (count == 1) {
            c1 = Integer.parseInt(temp);
            change[0] = 0;
        } else if (count == 2) {
            c2 = Integer.parseInt(temp);
            change[0] = 0;
        }
    }//GEN-LAST:event_card1ButtonActionPerformed

    private void card2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_card2ButtonActionPerformed
        String temp = cards.get(1);

        if (temp.equals("0")) {
            card2Button.setIcon(a);
        } else if (temp.equals("1")) {
            card2Button.setIcon(b);
        } else if (temp.equals("2")) {
            card2Button.setIcon(c);
        } else if (temp.equals("3")) {
            card2Button.setIcon(d);
        } else if (temp.equals("4")) {
            card2Button.setIcon(e);
        } else if (temp.equals("5")) {
            card2Button.setIcon(f);
        } else if (temp.equals("6")) {
            card2Button.setIcon(g);
        } else if (temp.equals("7")) {
            card2Button.setIcon(h);
        }

        count++;
        if (count == 1) {
            c1 = Integer.parseInt(temp);
            change[1] = 0;
        } else if (count == 2) {
            c2 = Integer.parseInt(temp);
            change[1] = 0;
        }
    }//GEN-LAST:event_card2ButtonActionPerformed

    private void card3ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_card3ButtonActionPerformed
        String temp = cards.get(2);

        if (temp.equals("0")) {
            card3Button.setIcon(a);
        } else if (temp.equals("1")) {
            card3Button.setIcon(b);
        } else if (temp.equals("2")) {
            card3Button.setIcon(c);
        } else if (temp.equals("3")) {
            card3Button.setIcon(d);
        } else if (temp.equals("4")) {
            card3Button.setIcon(e);
        } else if (temp.equals("5")) {
            card3Button.setIcon(f);
        } else if (temp.equals("6")) {
            card3Button.setIcon(g);
        } else if (temp.equals("7")) {
            card3Button.setIcon(h);
        }

        count++;
        if (count == 1) {
            c1 = Integer.parseInt(temp);
            change[2] = 0;
        } else {
            c2 = Integer.parseInt(temp);
            change[2] = 0;
        }
    }//GEN-LAST:event_card3ButtonActionPerformed

    private void card4ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_card4ButtonActionPerformed
        String temp = cards.get(3);

        if (temp.equals("0")) {
            card4Button.setIcon(a);
        } else if (temp.equals("1")) {
            card4Button.setIcon(b);
        } else if (temp.equals("2")) {
            card4Button.setIcon(c);
        } else if (temp.equals("3")) {
            card4Button.setIcon(d);
        } else if (temp.equals("4")) {
            card4Button.setIcon(e);
        } else if (temp.equals("5")) {
            card4Button.setIcon(f);
        } else if (temp.equals("6")) {
            card4Button.setIcon(g);
        } else if (temp.equals("7")) {
            card4Button.setIcon(h);
        }

        count++;
        if (count == 1) {
            c1 = Integer.parseInt(temp);
            change[3] = 0;
        } else {
            c2 = Integer.parseInt(temp);
            change[3] = 0;
        }
    }//GEN-LAST:event_card4ButtonActionPerformed

    private void card5ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_card5ButtonActionPerformed
        String temp = cards.get(4);

        if (temp.equals("0")) {
            card5Button.setIcon(a);
        } else if (temp.equals("1")) {
            card5Button.setIcon(b);
        } else if (temp.equals("2")) {
            card5Button.setIcon(c);
        } else if (temp.equals("3")) {
            card5Button.setIcon(d);
        } else if (temp.equals("4")) {
            card5Button.setIcon(e);
        } else if (temp.equals("5")) {
            card5Button.setIcon(f);
        } else if (temp.equals("6")) {
            card5Button.setIcon(g);
        } else if (temp.equals("7")) {
            card5Button.setIcon(h);
        }

        count++;
        if (count == 1) {
            c1 = Integer.parseInt(temp);
            change[4] = 0;
        } else {
            c2 = Integer.parseInt(temp);
            change[4] = 0;
        }
    }//GEN-LAST:event_card5ButtonActionPerformed

    private void card6ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_card6ButtonActionPerformed
        String temp = cards.get(5);

        if (temp.equals("0")) {
            card6Button.setIcon(a);
        } else if (temp.equals("1")) {
            card6Button.setIcon(b);
        } else if (temp.equals("2")) {
            card6Button.setIcon(c);
        } else if (temp.equals("3")) {
            card6Button.setIcon(d);
        } else if (temp.equals("4")) {
            card6Button.setIcon(e);
        } else if (temp.equals("5")) {
            card6Button.setIcon(f);
        } else if (temp.equals("6")) {
            card6Button.setIcon(g);
        } else if (temp.equals("7")) {
            card6Button.setIcon(h);
        }

        count++;
        if (count == 1) {
            c1 = Integer.parseInt(temp);
            change[5] = 0;
        } else {
            c2 = Integer.parseInt(temp);
            change[5] = 0;
        }
    }//GEN-LAST:event_card6ButtonActionPerformed

    private void card7ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_card7ButtonActionPerformed
        String temp = cards.get(6);

        if (temp.equals("0")) {
            card7Button.setIcon(a);
        } else if (temp.equals("1")) {
            card7Button.setIcon(b);
        } else if (temp.equals("2")) {
            card7Button.setIcon(c);
        } else if (temp.equals("3")) {
            card7Button.setIcon(d);
        } else if (temp.equals("4")) {
            card7Button.setIcon(e);
        } else if (temp.equals("5")) {
            card7Button.setIcon(f);
        } else if (temp.equals("6")) {
            card7Button.setIcon(g);
        } else if (temp.equals("7")) {
            card7Button.setIcon(h);
        }

        count++;
        if (count == 1) {
            c1 = Integer.parseInt(temp);
            change[6] = 0;
        } else {
            c2 = Integer.parseInt(temp);
            change[6] = 0;
        }

    }//GEN-LAST:event_card7ButtonActionPerformed

    private void card8ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_card8ButtonActionPerformed
        String temp = cards.get(7);

        if (temp.equals("0")) {
            card8Button.setIcon(a);
        } else if (temp.equals("1")) {
            card8Button.setIcon(b);
        } else if (temp.equals("2")) {
            card8Button.setIcon(c);
        } else if (temp.equals("3")) {
            card8Button.setIcon(d);
        } else if (temp.equals("4")) {
            card8Button.setIcon(e);
        } else if (temp.equals("5")) {
            card8Button.setIcon(f);
        } else if (temp.equals("6")) {
            card8Button.setIcon(g);
        } else if (temp.equals("7")) {
            card8Button.setIcon(h);
        }

        count++;
        if (count == 1) {
            c1 = Integer.parseInt(temp);
            change[7] = 0;
        } else {
            c2 = Integer.parseInt(temp);
            change[7] = 0;
        }

    }//GEN-LAST:event_card8ButtonActionPerformed

    private void card9ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_card9ButtonActionPerformed
        String temp = cards.get(8);

        if (temp.equals("0")) {
            card9Button.setIcon(a);
        } else if (temp.equals("1")) {
            card9Button.setIcon(b);
        } else if (temp.equals("2")) {
            card9Button.setIcon(c);
        } else if (temp.equals("3")) {
            card9Button.setIcon(d);
        } else if (temp.equals("4")) {
            card9Button.setIcon(e);
        } else if (temp.equals("5")) {
            card9Button.setIcon(f);
        } else if (temp.equals("6")) {
            card9Button.setIcon(g);
        } else if (temp.equals("7")) {
            card9Button.setIcon(h);
        }

        count++;
        if (count == 1) {
            c1 = Integer.parseInt(temp);
            change[8] = 0;
        } else {
            c2 = Integer.parseInt(temp);
            change[8] = 0;
        }
    }//GEN-LAST:event_card9ButtonActionPerformed

    private void card10ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_card10ButtonActionPerformed
        String temp = cards.get(9);

        if (temp.equals("0")) {
            card10Button.setIcon(a);
        } else if (temp.equals("1")) {
            card10Button.setIcon(b);
        } else if (temp.equals("2")) {
            card10Button.setIcon(c);
        } else if (temp.equals("3")) {
            card10Button.setIcon(d);
        } else if (temp.equals("4")) {
            card10Button.setIcon(e);
        } else if (temp.equals("5")) {
            card10Button.setIcon(f);
        } else if (temp.equals("6")) {
            card10Button.setIcon(g);
        } else if (temp.equals("7")) {
            card10Button.setIcon(h);
        }

        count++;
        if (count == 1) {
            c1 = Integer.parseInt(temp);
            change[9] = 0;
        } else {
            c2 = Integer.parseInt(temp);
            change[9] = 0;
        }
    }//GEN-LAST:event_card10ButtonActionPerformed

    private void card11ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_card11ButtonActionPerformed
        String temp = cards.get(10);

        if (temp.equals("0")) {
            card11Button.setIcon(a);
        } else if (temp.equals("1")) {
            card11Button.setIcon(b);
        } else if (temp.equals("2")) {
            card11Button.setIcon(c);
        } else if (temp.equals("3")) {
            card11Button.setIcon(d);
        } else if (temp.equals("4")) {
            card11Button.setIcon(e);
        } else if (temp.equals("5")) {
            card11Button.setIcon(f);
        } else if (temp.equals("6")) {
            card11Button.setIcon(g);
        } else if (temp.equals("7")) {
            card11Button.setIcon(h);
        }

        count++;
        if (count == 1) {
            c1 = Integer.parseInt(temp);
            change[10] = 0;
        } else {
            c2 = Integer.parseInt(temp);
            change[10] = 0;
        }
    }//GEN-LAST:event_card11ButtonActionPerformed

    private void card12ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_card12ButtonActionPerformed
        String temp = cards.get(11);

        if (temp.equals("0")) {
            card12Button.setIcon(a);
        } else if (temp.equals("1")) {
            card12Button.setIcon(b);
        } else if (temp.equals("2")) {
            card12Button.setIcon(c);
        } else if (temp.equals("3")) {
            card12Button.setIcon(d);
        } else if (temp.equals("4")) {
            card12Button.setIcon(e);
        } else if (temp.equals("5")) {
            card12Button.setIcon(f);
        } else if (temp.equals("6")) {
            card12Button.setIcon(g);
        } else if (temp.equals("7")) {
            card12Button.setIcon(h);
        }

        count++;
        if (count == 1) {
            c1 = Integer.parseInt(temp);
            change[11] = 0;
        } else {
            c2 = Integer.parseInt(temp);
            change[11] = 0;
        }
    }//GEN-LAST:event_card12ButtonActionPerformed

    private void card13ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_card13ButtonActionPerformed
        String temp = cards.get(12);

        if (temp.equals("0")) {
            card13Button.setIcon(a);
        } else if (temp.equals("1")) {
            card13Button.setIcon(b);
        } else if (temp.equals("2")) {
            card13Button.setIcon(c);
        } else if (temp.equals("3")) {
            card13Button.setIcon(d);
        } else if (temp.equals("4")) {
            card13Button.setIcon(e);
        } else if (temp.equals("5")) {
            card13Button.setIcon(f);
        } else if (temp.equals("6")) {
            card13Button.setIcon(g);
        } else if (temp.equals("7")) {
            card13Button.setIcon(h);
        }

        count++;
        if (count == 1) {
            c1 = Integer.parseInt(temp);
            change[12] = 0;
        } else {
            c2 = Integer.parseInt(temp);
            change[12] = 0;
        }
    }//GEN-LAST:event_card13ButtonActionPerformed

    private void card14ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_card14ButtonActionPerformed
        String temp = cards.get(13);

        if (temp.equals("0")) {
            card14Button.setIcon(a);
        } else if (temp.equals("1")) {
            card14Button.setIcon(b);
        } else if (temp.equals("2")) {
            card14Button.setIcon(c);
        } else if (temp.equals("3")) {
            card14Button.setIcon(d);
        } else if (temp.equals("4")) {
            card14Button.setIcon(e);
        } else if (temp.equals("5")) {
            card14Button.setIcon(f);
        } else if (temp.equals("6")) {
            card14Button.setIcon(g);
        } else if (temp.equals("7")) {
            card14Button.setIcon(h);
        }

        count++;
        if (count == 1) {
            c1 = Integer.parseInt(temp);
            change[13] = 0;
        } else {
            c2 = Integer.parseInt(temp);
            change[13] = 0;
        }
     }//GEN-LAST:event_card14ButtonActionPerformed

    private void card15ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_card15ButtonActionPerformed
        String temp = cards.get(14);

        if (temp.equals("0")) {
            card15Button.setIcon(a);
        } else if (temp.equals("1")) {
            card15Button.setIcon(b);
        } else if (temp.equals("2")) {
            card15Button.setIcon(c);
        } else if (temp.equals("3")) {
            card15Button.setIcon(d);
        } else if (temp.equals("4")) {
            card15Button.setIcon(e);
        } else if (temp.equals("5")) {
            card15Button.setIcon(f);
        } else if (temp.equals("6")) {
            card15Button.setIcon(g);
        } else if (temp.equals("7")) {
            card15Button.setIcon(h);
        }

        count++;
        if (count == 1) {
            c1 = Integer.parseInt(temp);
            change[14] = 0;
        } else {
            c2 = Integer.parseInt(temp);
            change[14] = 0;
        }
    }//GEN-LAST:event_card15ButtonActionPerformed

    private void card16ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_card16ButtonActionPerformed
        String temp = cards.get(15);

        if (temp.equals("0")) {
            card16Button.setIcon(a);
        } else if (temp.equals("1")) {
            card16Button.setIcon(b);
        } else if (temp.equals("2")) {
            card16Button.setIcon(c);
        } else if (temp.equals("3")) {
            card16Button.setIcon(d);
        } else if (temp.equals("4")) {
            card16Button.setIcon(e);
        } else if (temp.equals("5")) {
            card16Button.setIcon(f);
        } else if (temp.equals("6")) {
            card16Button.setIcon(g);
        } else if (temp.equals("7")) {
            card16Button.setIcon(h);
        }

        count++;
        if (count == 1) {
            c1 = Integer.parseInt(temp);
            change[15] = 0;
        } else {
            c2 = Integer.parseInt(temp);
            change[15] = 0;
        }
     }//GEN-LAST:event_card16ButtonActionPerformed

    private void guessButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guessButtonActionPerformed
        count = 0;
        if (c1 == c2) {
            cardsLeft = cardsLeft - 2;
            for (int y = 1; y <= 2; y++) {
                if (change[0] == 0) {
                    card1Button.setIcon(done);
                    change[0] = 2;
                } else if (change[1] == 0) {
                    card2Button.setIcon(done);
                    change[1] = 2;
                } else if (change[2] == 0) {
                    card3Button.setIcon(done);
                    change[2] = 2;
                } else if (change[3] == 0) {
                    card4Button.setIcon(done);
                    change[3] = 2;
                } else if (change[4] == 0) {
                    card5Button.setIcon(done);
                    change[4] = 2;
                } else if (change[5] == 0) {
                    card6Button.setIcon(done);
                    change[5] = 2;
                } else if (change[6] == 0) {
                    card7Button.setIcon(done);
                    change[6] = 2;
                } else if (change[7] == 0) {
                    card8Button.setIcon(done);
                    change[7] = 2;
                } else if (change[8] == 0) {
                    card9Button.setIcon(done);
                    change[8] = 2;
                } else if (change[9] == 0) {
                    card10Button.setIcon(done);
                    change[9] = 2;
                } else if (change[10] == 0) {
                    card11Button.setIcon(done);
                    change[10] = 2;
                } else if (change[11] == 0) {
                    card12Button.setIcon(done);
                    change[11] = 2;
                } else if (change[12] == 0) {
                    card13Button.setIcon(done);
                    change[12] = 2;
                } else if (change[13] == 0) {
                    card14Button.setIcon(done);
                    change[13] = 2;
                } else if (change[14] == 0) {
                    card15Button.setIcon(done);
                    change[14] = 2;
                } else if (change[15] == 0) {
                    card16Button.setIcon(done);
                    change[15] = 2;
                }
            }
        } else {
            for (int y = 1; y <= 2; y++) {
                if (change[0] == 0) {
                    card1Button.setIcon(back);
                    change[0] = 1;
                } else if (change[1] == 0) {
                    card2Button.setIcon(back);
                    change[1] = 1;
                } else if (change[2] == 0) {
                    card3Button.setIcon(back);
                    change[2] = 1;
                } else if (change[3] == 0) {
                    card4Button.setIcon(back);
                    change[3] = 1;
                } else if (change[4] == 0) {
                    card5Button.setIcon(back);
                    change[4] = 1;
                } else if (change[5] == 0) {
                    card6Button.setIcon(back);
                    change[5] = 1;
                } else if (change[6] == 0) {
                    card7Button.setIcon(back);
                    change[6] = 1;
                } else if (change[7] == 0) {
                    card8Button.setIcon(back);
                    change[7] = 1;
                } else if (change[8] == 0) {
                    card9Button.setIcon(back);
                    change[8] = 1;
                } else if (change[9] == 0) {
                    card10Button.setIcon(back);
                    change[9] = 1;
                } else if (change[10] == 0) {
                    card11Button.setIcon(back);
                    change[10] = 1;
                } else if (change[11] == 0) {
                    card12Button.setIcon(back);
                    change[11] = 1;
                } else if (change[12] == 0) {
                    card13Button.setIcon(back);
                    change[12] = 1;
                } else if (change[13] == 0) {
                    card14Button.setIcon(back);
                    change[13] = 1;
                } else if (change[14] == 0) {
                    card15Button.setIcon(back);
                    change[14] = 1;
                } else if (change[15] == 0) {
                    card16Button.setIcon(back);
                    change[15] = 1;
                }
            }
        }
        if (cardsLeft == 0) {
            //jTextField1.setText("Congratulations, you win!");
        }
    }//GEN-LAST:event_guessButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        //exits the program
        System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MemoryUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MemoryUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MemoryUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MemoryUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MemoryUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton card10Button;
    private javax.swing.JButton card11Button;
    private javax.swing.JButton card12Button;
    private javax.swing.JButton card13Button;
    private javax.swing.JButton card14Button;
    private javax.swing.JButton card15Button;
    private javax.swing.JButton card16Button;
    private javax.swing.JButton card1Button;
    private javax.swing.JButton card2Button;
    private javax.swing.JButton card3Button;
    private javax.swing.JButton card4Button;
    private javax.swing.JButton card5Button;
    private javax.swing.JButton card6Button;
    private javax.swing.JButton card7Button;
    private javax.swing.JButton card8Button;
    private javax.swing.JButton card9Button;
    private javax.swing.JButton exitButton;
    private javax.swing.JButton guessButton;
    private javax.swing.JLabel outputLabel;
    private javax.swing.JButton playButton;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
